const tempDatabase = [
  {
    userid: 1,
    name: "Rahul Sharma",
    division: "Division A",
    subDivision: "Sub Division A1",
    location: "Bengaluru",
  },
  {
    userid: 2,
    name: "Anjali Rao",
    division: "Division A",
    subDivision: "Sub Division A2",
    location: "Mysuru",
  },
  {
    userid: 3,
    name: "Karthik Gowda",
    division: "Division B",
    subDivision: "Sub Division B1",
    location: "Mangaluru",
  },
  {
    userid: 4,
    name: "Sneha Kulkarni",
    division: "Division B",
    subDivision: "Sub Division B2",
    location: "Hubballi",
  },
  {
    userid: 5,
    name: "Manoj Patil",
    division: "Division C",
    subDivision: "Sub Division C1",
    location: "Belagavi",
  },
  {
    userid: 6,
    name: "Pooja Shetty",
    division: "Division C",
    subDivision: "Sub Division C2",
    location: "Dharwad",
  },
  {
    userid: 7,
    name: "Vinay Kumar",
    division: "Division A",
    subDivision: "Sub Division A1",
    location: "Shivamogga",
  },
  {
    userid: 8,
    name: "Lakshmi Murthy",
    division: "Division B",
    subDivision: "Sub Division B1",
    location: "Kalaburagi",
  },
  {
    userid: 9,
    name: "Rohan Deshpande",
    division: "Division C",
    subDivision: "Sub Division C2",
    location: "Raichur",
  },
  {
    userid: 10,
    name: "Deepika Joshi",
    division: "Division A",
    subDivision: "Sub Division A2",
    location: "Udupi",
  },
  {
    userid: 11,
    name: "Arjun Prasad",
    division: "Division C",
    subDivision: "Sub Division C1",
    location: "Tumakuru",
  },
  {
    userid: 12,
    name: "Swathi Bhat",
    division: "Division B",
    subDivision: "Sub Division B2",
    location: "Bidar",
  },
  {
    userid: 13,
    name: "Ganesh Naik",
    division: "Division A",
    subDivision: "Sub Division A1",
    location: "Chikkamagaluru",
  },
  {
    userid: 14,
    name: "Meghana Reddy",
    division: "Division B",
    subDivision: "Sub Division B1",
    location: "Chitradurga",
  },
  {
    userid: 15,
    name: "Pradeep Shenoy",
    division: "Division C",
    subDivision: "Sub Division C2",
    location: "Hassan",
  },
];

export default tempDatabase;
